### PR TITLE
Add StartHttpSpan overload for HttpRequestMessage

### PR DESCRIPTION
**Pull request by dustinsoftware**
I did not find any tests to update, but can confirm this works as expected locally.

### CODE REVIEW

**Comment by bgrainger** [comment]
The preferred approach is to use `CreateHttpMessageHandler`; do we absolutely need to add another API?

**Comment by dustinsoftware** [comment]
`Faithlife.WebRequests.WebServiceRequestSettings` exposes a `StartTrace` property. Without this change, it doesn't look like that can be used with Faithlife Tracing.. should that property be deprecated on `Faithlife.WebRequests`?

**Comment by bgrainger** [comment]
Refactor `TracingHttpMessageHandler.ProcessRequest` to use `var requestSpan = (ITraceSpan) m_traceSpanProvider.StartHttpSpan(request);` or similar.

**Comment by bgrainger** [comment]
> should that property be deprecated

I think so; we should most likely use `WebServiceRequestSettings.GetHttpClient` to provide a custom HttpClient.

**Comment by dustinsoftware** [comment]
Closing in favor of deprecating `StartTrace`

**Comment by bgrainger** [comment]
This can be accomplished by using `WebServiceRequestSettings.GetHttpClient` to inject the return value of `CreateHttpMessageHandler`.

**Pull request closed without merging**
